### ISSUE TITLE
Deserialize json request.

### ISSUE THREAD

**Issue by ghost** [advancedrei/sendgridplus-csharp#11]
Hi,

I am using this code:
 var events = Events.GetEvents<Email_Status>(Request.InputStream);

but it fails to deserialize the json:

Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: ]. Path '', line 196, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at SendGrid.Events.GetEvents(String json)
   at SendGrid.Events.GetEvents(Stream inputStream)
   at itsperfect.ResponseHandler.Mvc.Controllers.EmailController.CatchMailEvent() 

When i look at the source code i see that GetEvents(string json) cant find reference to:
JsonConvert.DeserializeObject

added reference but it still doesent work.

Issue posted on stackoverflow: http://stackoverflow.com/questions/20742067

**Comment by kquinbar** [comment]
I am having this same issue. wondering if its a bug in sendgridplus or did sendgrid possibly change their event api?

**Comment by robertmclaws** [comment]
I'll see if I can take a look at this over the weekend. Thanks for reporting!

**Comment by ghost** [comment]
Solved by putting trim before deserializing is done.

**Comment by kquinbar** [comment]
so Stefan, you made an update to the source code to trim the string coming in? I am assuming either this was overlooked in the current release version or maybe SendGrid changed their event api?

advancedrei, were you able to look at this issue yet, and will you be releasing a fix soon?

**Comment by robertmclaws** [comment]
Yeah I'll try to get a build out in the next 24 hours.

**Comment by kquinbar** [comment]
will there be a nuget release too? thanks for the quick reply.

**Comment by kquinbar** [comment]
For the time being, I just trimmed the json pushed into your method and it works as expected, but yeah once you get this new build out, let me know.

Thanks!

**Comment by robertmclaws** [comment]
Sorry for the delay. I have pushed a new build to NuGet (3.1.0-Beta2) that handles this and a number of other issues. I'm going to consider this issue closed. Please re-open if you have any problems. Thanks!

**Comment by AgentTy** [comment]
First, let me say THANK YOU THANK YOU THANK YOU THANK YOU for this library!!!!!!

Now to business, it appears that this bug is still happening... at least for me. Today I downloaded the latest version from here: https://github.com/advancedrei/sendgridplus-csharp/tree/master, Installed it and migrated to SendGrids Event API v3.

At launch time I started getting lots of this same error, and the solution was to do this....
var events = Events.GetEvents<CustomEventData>(reader.ReadToEnd().TrimEnd());

instead of this...
var events = Events.GetEvents<CustomEventData>(context.Request.InputStream);

I'm up and running, so no crisis, just wanted to contribute to the community best I can. Thank you again soooooo much, I'd this v3 transition seemed so daunting till I saw that you had already done it.
-Ty
